### ISSUE TITLE
A-USF01 Tank - incorrect fuel capacity

### ISSUE THREAD

**Issue by TykoTek** [Tantares/TantaresLV#31]
The tank has much lower capacity than it's volume should be able to contain.

Here's a comparison of the A-USF01 with your C-81, the Stock FLT-100 and a procedural tank of approx the same size:

![image](https://user-images.githubusercontent.com/22890228/58768537-9929a800-8551-11e9-9074-6b107c6d053c.png)

**Comment by Tantares** [comment]
Fixed tank amounts, thanks!
